import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import { RoomProvider } from "./context/roomContext";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        poppins.variable,
        "font-poppins",
        poppins.variable,
        "dark",
      )}
    >
      <body className="h-full min-h-svh">
        <RoomProvider>
          <TooltipProvider>{children}</TooltipProvider>
        </RoomProvider>
      </body>
    </html>
  );
}
